name: beam-migrate-cli

dependencies:
  - base
  - beam-core
  - beam-migrate
  - editor-open
  - lens
  - optparse-applicative
  - unix
  - filepath
  - directory
  - fgl
  - text
  - bytestring
  - vector
  - containers
  - process
  - time
  - aeson

default-extensions:
  - GADTs
  - ScopedTypeVariables
  - TemplateHaskell
  - RankNTypes
  - LambdaCase
  - DeriveAnyClass
  - KindSignatures
  - DeriveGeneric
  - MultiParamTypeClasses
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies

library:
  exposed-modules:
    Database.Beam.Migrate.Cli
  other-modules:
    - Database.Beam.Migrate.Cli.Types
    - Database.Beam.Migrate.Cli.Registry
    - Database.Beam.Migrate.Cli.VC
    - Database.Beam.Migrate.Cli.Database
    - Database.Beam.Migrate.Cli.Commands.Add
    - Database.Beam.Migrate.Cli.Commands.Common

executables:
  beam-migrate-cli-test:
    main: Pagila.hs
    source-dirs: example
    dependencies:
      - beam-migrate-cli
      - beam-sqlite
      - sqlite-simple
