name: beam-migrate-cli

dependencies:
  - base
  - beam-core
  - beam-migrate
  - beam-migrate-cli-engine
  - editor-open
  - lens
  - optparse-applicative
  - unix
  - filepath
  - directory
  - fgl
  - text
  - bytestring
  - vector
  - containers
  - unordered-containers
  - mtl
  - process
  - time
  - aeson
  - prettyprinter
  - prettyprinter-ansi-terminal
  - cryptonite
  - memory

default-extensions:
  - GADTs
  - ScopedTypeVariables
  - TemplateHaskell
  - RankNTypes
  - LambdaCase
  - DeriveAnyClass
  - KindSignatures
  - DeriveGeneric
  - MultiParamTypeClasses
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies
  - ConstraintKinds
  - StandaloneDeriving
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - TypeApplications
  - TypeOperators
  - TupleSections

library:
  exposed-modules:
    Database.Beam.Migrate.Cli
  other-modules:
    - Database.Beam.Migrate.Cli.Types
    - Database.Beam.Migrate.Cli.Registry
    - Database.Beam.Migrate.Cli.VC
    - Database.Beam.Migrate.Cli.Commands.Abort
    - Database.Beam.Migrate.Cli.Commands.Add
    - Database.Beam.Migrate.Cli.Commands.Commit
    - Database.Beam.Migrate.Cli.Commands.Common
    - Database.Beam.Migrate.Cli.Commands.Diff
    - Database.Beam.Migrate.Cli.Commands.Edit
    - Database.Beam.Migrate.Cli.Commands.Log
    - Database.Beam.Migrate.Cli.Commands.ManageDb
    - Database.Beam.Migrate.Cli.Commands.Migrate
    - Database.Beam.Migrate.Cli.Commands.Pickle
    - Database.Beam.Migrate.Cli.Commands.Status
    - Database.Beam.Migrate.Cli.Commands.Verify
    - Database.Beam.Migrate.Cli.Message

executables:
  beam-migrate-cli-test:
    main: Pagila.hs
    source-dirs: example
    dependencies:
      - beam-migrate-cli
      - beam-sqlite
      - sqlite-simple
